# Kubernetes deployment for model server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server
  labels:
    app: model-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: model-s3-access-sa   # IRSA-linked service account
      containers:
        - name: model-server
          image: your-dockerhub-username/model-server:latest
          ports:
            - containerPort: 8000
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: s3_bucket
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
s