# Kubernetes service definition
apiVersion: v1
kind: Service
metadata:
  name: model-server
  labels:
    app: model-server
spec:
  type: LoadBalancer
  selector:
    app: model-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
